<?php
declare(strict_types=1);
require_once __DIR__ . '/api/user_auth.php';
$user = requireUser();
$orders = DB::userOrders((int)$user['id']);
$csrf = userCsrfToken();
function e(string $value): string { return htmlspecialchars($value, ENT_QUOTES, 'UTF-8'); }
function orderStatus(string $status): string { return ['NOTPAY'=>'待支付','SUCCESS'=>'支付成功','CLOSED'=>'已关闭','REFUND'=>'已退款'][$status] ?? $status; }
?><!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>用户中心 · 梵燊科技</title><style>
:root{--bg:#080c16;--panel:#0d1320;--line:rgba(255,255,255,.1);--text:#e2e8f0;--muted:#94a3b8;--cyan:#38bdf8}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--text);font-family:-apple-system,BlinkMacSystemFont,"Segoe UI","Microsoft YaHei",sans-serif}.top{border-bottom:1px solid var(--line)}.top-inner{max-width:1100px;margin:auto;padding:17px 22px;display:flex;justify-content:space-between;align-items:center}.top a,.link-btn{color:var(--cyan);text-decoration:none;background:none;border:0;cursor:pointer;font:inherit}.wrap{max-width:1100px;margin:auto;padding:34px 22px 70px}.intro{margin-bottom:25px}.intro h1{margin:0 0 7px}.intro p{color:var(--muted);margin:0}.layout{display:grid;grid-template-columns:320px 1fr;gap:20px}.panel{background:var(--panel);border:1px solid var(--line);border-radius:8px;padding:22px;margin-bottom:20px}.panel h2{font-size:1.05rem;margin:0 0 16px}.field{margin-bottom:14px}.field label{display:block;color:var(--muted);font-size:.84rem;margin-bottom:6px}.field input{width:100%;padding:10px 11px;border:1px solid var(--line);border-radius:6px;background:#111827;color:#fff;font:inherit}.readonly{color:var(--muted);font-size:.92rem}.btn{padding:10px 15px;border:0;border-radius:6px;background:#2563eb;color:#fff;cursor:pointer}.danger{background:#b91c1c}.feedback{min-height:20px;margin-top:10px;font-size:.85rem;color:#86efac}.feedback.error{color:#fca5a5}.orders{overflow:auto}table{width:100%;border-collapse:collapse;font-size:.86rem;min-width:620px}th,td{text-align:left;padding:11px 9px;border-bottom:1px solid var(--line)}th{color:var(--muted);font-weight:500}.empty{color:var(--muted);padding:30px 0;text-align:center}.delete-copy{color:var(--muted);font-size:.86rem;line-height:1.7}@media(max-width:760px){.layout{grid-template-columns:1fr}.wrap{padding-top:24px}}
</style></head><body><header class="top"><div class="top-inner"><a href="/">梵燊科技</a><div><a href="shop.php">商城</a>　<button class="link-btn" id="logoutBtn">退出</button></div></div></header><main class="wrap"><div class="intro"><h1><?= e((string)$user['nickname']) ?>，你好</h1><p>管理个人资料、登录密码和商城订单</p></div><div class="layout"><aside><section class="panel"><h2>基本资料</h2><div class="field"><label>手机号码</label><div class="readonly"><?= e(substr((string)$user['phone'],0,3).'****'.substr((string)$user['phone'],-4)) ?></div></div><div class="field"><label>注册时间</label><div class="readonly"><?= e((string)$user['created_at']) ?></div></div><form data-action="profile"><div class="field"><label>昵称</label><input name="nickname" minlength="2" maxlength="30" value="<?= e((string)$user['nickname']) ?>" required></div><button class="btn" type="submit">保存资料</button><div class="feedback"></div></form></section><section class="panel"><h2>修改密码</h2><form data-action="password"><div class="field"><label>当前密码</label><input type="password" name="current_password" required></div><div class="field"><label>新密码</label><input type="password" name="new_password" minlength="8" maxlength="72" required></div><button class="btn" type="submit">修改密码</button><div class="feedback"></div></form></section><section class="panel"><h2>注销账号</h2><p class="delete-copy">注销后个人资料将匿名化，账号无法恢复。依法需要保留的支付和退款记录仍会保存。</p><form data-action="delete" onsubmit="return confirm('确定永久注销账号？此操作不可撤销。')"><div class="field"><label>输入密码确认</label><input type="password" name="password" required></div><label class="delete-copy"><input type="checkbox" name="confirm" required> 我已了解注销后果</label><br><button class="btn danger" type="submit">永久注销账号</button><div class="feedback"></div></form></section></aside><section><div class="panel"><h2>我的订单</h2><div class="orders"><?php if(!$orders):?><div class="empty">暂无订单</div><?php else:?><table><thead><tr><th>订单号</th><th>商品</th><th>金额</th><th>支付状态</th><th>退款状态</th><th>创建时间</th></tr></thead><tbody><?php foreach($orders as $order):?><tr><td><?=e((string)$order['out_trade_no'])?></td><td><?=e((string)($order['product_name']?:$order['description']))?></td><td>¥<?=number_format((int)$order['amount']/100,2)?></td><td><?=e(orderStatus((string)$order['status']))?></td><td><?=e((string)($order['refund']['status']??'未退款'))?></td><td><?=e((string)$order['created_at'])?></td></tr><?php endforeach;?></tbody></table><?php endif;?></div></div></section></div></main><script>
const csrf=<?=json_encode($csrf)?>;async function call(action,data){const r=await fetch('api/user.php?action='+action,{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-Token':csrf},body:JSON.stringify(data)});const d=await r.json();if(!r.ok||!d.ok)throw new Error(d.message||'操作失败');return d;}
document.querySelectorAll('form[data-action]').forEach(form=>form.addEventListener('submit',async e=>{e.preventDefault();const action=form.dataset.action,fd=new FormData(form),data=Object.fromEntries(fd.entries());data.confirm=fd.has('confirm');const feedback=form.querySelector('.feedback');feedback.className='feedback';feedback.textContent='';const button=form.querySelector('button');button.disabled=true;try{const d=await call(action,data);feedback.textContent=d.message;if(action==='delete')location.href='/';if(action==='profile')setTimeout(()=>location.reload(),500);if(action==='password')form.reset();}catch(err){feedback.className='feedback error';feedback.textContent=err.message;}finally{button.disabled=false;}}));
document.getElementById('logoutBtn').onclick=async()=>{try{await call('logout',{});}finally{location.href='/';}};
</script><footer style="max-width:1100px;margin:32px auto 40px;padding:0 20px;color:#64748b;text-align:center;font-size:.8rem;line-height:1.8">© 2026 清远梵燊人工智能科技有限公司<br><a href="https://beian.miit.gov.cn/" target="_blank" rel="noopener" style="color:#67e8f9">粤ICP备2026080863号</a> | <a href="https://beian.mps.gov.cn/#/query/webSearch?code=44180202001121" target="_blank" rel="noopener" style="color:#67e8f9">粤公网安备44180202001121号</a></footer></body></html>
